import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import { useRouter } from "next/router";
import { useEffect } from "react";
import img from '../Completeimg.png';

export default function CompleteSignup() {
  const router = useRouter();


  return (
    <>
      <Head>
        <title>Signup Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex justify-content-center align-items-center vh-100" style={{ backgroundColor: '#DDD0DC' }}>
       
          <p>Hello User!!</p>
      </div>
    </>
  );
}
