import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import { useRouter } from "next/router";
import { useEffect } from "react";
import img from '../Completeimg.png';

export default function CompleteSignup() {
  const router = useRouter();

  useEffect(() => {
    const timer = setTimeout(() => {
      router.push('/signin');
    }, 2000); 
    return () => clearTimeout(timer); 
  }, [router]);

  return (
    <>
      <Head>
        <title>Signup Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="d-flex justify-content-center align-items-center vh-100" style={{ backgroundColor: '#DDD0DC' }}>
        <div className="card" style={{ width: '32rem', backgroundColor: 'white', padding: '20px', borderRadius: '15px', textAlign: 'center' }}>
          <img 
            src={img.src} 
            alt="Checkmark"
            style={{ width: '100px', margin: '20px auto', borderRadius: '50%' }}
          />
          <p>Your phone number and email has been successfully verified.</p>
        </div>
      </div>
    </>
  );
}
