import Head from "next/head";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { useState } from 'react';
import { useRouter } from "next/router";
import Logo from "../Logo";
import superagent from 'superagent';
import Cookies from 'js-cookie';
import nookies from 'nookies';
import toast, { Toaster } from "react-hot-toast";
import { ArrowLeftOutlined } from "@ant-design/icons";

export default function SignUp() {
  const router = useRouter();
  const [showPassword, setShowPassword] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');
  const [selectedCountryCode, setSelectedCountryCode] = useState('');
  const [mobileNumber, setMobileNumber] = useState('');

  const togglePasswordVisibility = () => {
    setShowPassword(!showPassword);
  };

  const handleSignUp = async () => {
    try {
      const response = await superagent.post('https://master.project.henceforthsolutions.com:3000/signup')
        .send({
          first_name: name,
          email: email,
          password: password,
          country_code: selectedCountryCode,
          phone: mobileNumber,
        });
        Cookies.set('authToken', response.body.access_token);
      console.log('Account registered successfully:', response.body);
      nookies.set(null, 'token', response.body.token, { path: '/' });
      router.push('/verifyemail'); 
    } catch (error:any) {
      toast.error(error.response.body.message)
          }
  };

  return (
    <>
      <Head>
        <title>Signup Module</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster
  position="top-right"
  reverseOrder={false}
/>
      <div className="d-flex justify-content-center align-items-center vh-100" style={{ backgroundColor: '#DDD0DC' }}>
        <div className="card" style={{ width: '32rem', backgroundColor: 'white', padding: '20px', borderRadius: '15px' }}>
        <ArrowLeftOutlined onClick={() => router.push('/')} style={{ cursor: 'pointer', fontSize: '1.5rem', position: 'absolute', top: '20px', right: '470px' }} />

          <div style={{ textAlign: 'center' }}>
            <Logo />
          </div>
          <h2 className="text-center mb-4">Sign up</h2>
          <div className="form-group">
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <span className="input-group-text"><i className="bi bi-person"></i></span>
              </div>
              <input
                type="text"
                className="form-control"
                placeholder="Name"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </div>
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <span className="input-group-text"><i className="bi bi-envelope"></i></span>
              </div>
              <input
                type="email"
                className="form-control"
                placeholder="Email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <span className="input-group-text"><i className="bi bi-lock"></i></span>
              </div>
              <input
                type={showPassword ? "text" : "password"}
                className="form-control"
                placeholder="Password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <div className="input-group-append">
                <span className="input-group-text" onClick={togglePasswordVisibility}>
                  <i className={showPassword ? "bi bi-eye-slash" : "bi bi-eye"}></i>
                </span>
              </div>
            </div>
            <div className="input-group mb-3">
              <div className="input-group-prepend">
                <span className="input-group-text"><i className="bi bi-telephone"></i></span>
              </div>
              <select
              
                className="form-control"
                value={selectedCountryCode}
                onChange={(e) => setSelectedCountryCode(e.target.value)}
              >
                <option value="">Select</option>
                <option value="+91">India (+91)</option>
                <option value="+1">United States (+1)</option>
                <option value="+44">United Kingdom (+44)</option>
              </select>
              <input
              style={{width:'254px'}}
                type="text"
                className="form-control"
                placeholder="Mobile number"
                value={mobileNumber}
                onChange={(e) => setMobileNumber(e.target.value)}
              />
            </div>
          </div>
          <div>
            <input className="btn btn-link p-0 ml-2" type="checkbox" /> 
            <p style={{ fontSize: '12px' }}>By clicking create account you agree to the Terms Of Service and Privacy Policy</p>
          </div>
          <button
            type="button"
            className="btn btn-danger"
            onClick={handleSignUp}
            disabled={!name || !email || !password || !selectedCountryCode || !mobileNumber}
          >
            Sign up
          </button>
          <div className="d-flex align-items-center" style={{ marginTop: '20px' }}>
            <p className="mb-0">Already have an account?</p>
            <button className="btn btn-link p-0 ml-2" onClick={() => router.push('/signin')}>Sign in</button>
          </div>
        </div>
      </div>
    </>
  );
}
